<?php
declare(strict_types=1);
require dirname(__DIR__) . '/core/CanonicalOrigin.php';
use FBL\CanonicalOrigin;
$checks = 0;
$assert = static function (bool $ok, string $label) use (&$checks): void {
    $checks++;
    if (!$ok) throw new RuntimeException($label);
};
$s = ['HTTP_HOST' => 'cms.example', 'HTTPS' => 'on', 'REQUEST_URI' => '/de/posts/a?x=1%2F2&y=3', 'REMOTE_ADDR' => '10.0.0.2'];
$assert(CanonicalOrigin::redirectUrl('https://cms.example', $s) === null, 'Correct origin');
$s['HTTP_HOST'] = 'www.cms.example';
$url = CanonicalOrigin::redirectUrl('https://cms.example', $s);
$assert($url === 'https://cms.example/de/posts/a?x=1%2F2&y=3', 'Encoded path, query, locale');
$s['HTTP_HOST'] = 'cms.example:443';
$assert(CanonicalOrigin::redirectUrl('https://cms.example', $s) === null, 'Default port has no loop');
unset($s['HTTPS']);
$s['HTTP_X_FORWARDED_PROTO'] = 'https';
$assert(CanonicalOrigin::redirectUrl('https://cms.example', $s, ['10.0.0.2']) === null, 'Trusted proxy');
$assert(CanonicalOrigin::redirectUrl('https://cms.example', $s) !== null, 'Spoofed proxy ignored');
$s['HTTP_HOST'] = 'evil.example';
$s['REQUEST_URI'] = '/cms/en/?q=%D0%BC';
$assert(CanonicalOrigin::redirectUrl('https://cms.example/cms', $s) === 'https://cms.example/cms/en/?q=%D0%BC', 'Subdirectory retained once');
$s['REQUEST_URI'] = "/foo\r\nLocation: https://evil.example";
$assert(CanonicalOrigin::redirectUrl('https://cms.example', $s) === 'https://cms.example/', 'Header injection rejected');
$assert(CanonicalOrigin::redirectUrl('https://user:pass@cms.example', $s) === null, 'Invalid config rejected');
$s = ['HTTP_HOST' => '[::1]:8080', 'REQUEST_URI' => '/'];
$assert(CanonicalOrigin::redirectUrl('http://[::1]:8080', $s) === null, 'IPv6 development port');
$source = file_get_contents(dirname(__DIR__) . '/public/index.php');
$assert(strpos($source, 'CanonicalOrigin::redirectUrl') < strpos($source, '$vendorAutoload'), 'Redirect precedes application startup');
echo "$checks canonical origin checks passed\n";
