<?php

namespace Fireball\CameraManager;

use RuntimeException;

final class StreamsFilePublisher
{
    public const BEGIN_MARKER = '# FIREBALL CAMERA MANAGER: BEGIN';
    public const END_MARKER = '# FIREBALL CAMERA MANAGER: END';

    public function __construct(
        private readonly ProcessRunner $processRunner = new ProcessRunner()
    ) {
    }

    public function renderManagedBlock(array $streams, bool $redactSecrets = false): string
    {
        usort($streams, static fn(array $left, array $right): int => strnatcasecmp(
            (string)$left['stream_key'],
            (string)$right['stream_key']
        ));

        $lines = [
            '    ' . self::BEGIN_MARKER,
            '    # Generated by FIREBALL CMS. Edit cameras in Camera Manager, not here.',
        ];
        foreach ($streams as $stream) {
            $key = (string)($stream['stream_key'] ?? '');
            $url = (string)($stream['rtsp_url'] ?? '');
            if (!preg_match('/^[a-zA-Z0-9_-]{1,64}$/', $key)) {
                throw new RuntimeException('Invalid stream key: ' . $key);
            }
            if (!str_starts_with($url, 'rtsp://') || str_contains($url, "\n") || str_contains($url, "\r")) {
                throw new RuntimeException('Invalid RTSP URL for stream ' . $key . '.');
            }
            if ($redactSecrets) {
                $url = preg_replace('~^(rtsp://)[^@]+@~', '$1***:***@', $url) ?? $url;
            }
            $lines[] = "    '" . $this->perlSingleQuoted($key) . "' => '" . $this->perlSingleQuoted($url) . "',";
        }
        $lines[] = '    ' . self::END_MARKER;

        return implode("\n", $lines);
    }

    /** @return array{stream_count:int, backup_path:string, syntax_output:string, restarted:bool, restart_output:string} */
    public function publish(array $streams, array $settings): array
    {
        $path = $this->validatedStreamsPath((string)($settings['streams_file_path'] ?? ''));
        $perlBinary = $this->validatedBinary((string)($settings['perl_binary'] ?? '/usr/bin/perl'), 'perl');
        $lock = fopen($path . '.fireball-camera-manager.lock', 'c');
        if ($lock === false || !flock($lock, LOCK_EX | LOCK_NB)) {
            if (is_resource($lock)) {
                fclose($lock);
            }
            throw new RuntimeException('Another camera publication is already running.');
        }

        $temporaryPath = '';
        try {
            $original = file_get_contents($path);
            if ($original === false) {
                throw new RuntimeException('Unable to read streams.pl.');
            }

            $updated = $this->merge($original, $this->renderManagedBlock($streams), $streams);
            $directory = dirname($path);
            $temporaryPath = tempnam($directory, '.camera-manager-');
            if ($temporaryPath === false) {
                throw new RuntimeException('Unable to create a temporary streams.pl file.');
            }
            if (file_put_contents($temporaryPath, $updated, LOCK_EX) === false) {
                throw new RuntimeException('Unable to write the temporary streams.pl file.');
            }
            $mode = fileperms($path);
            if ($mode !== false) {
                @chmod($temporaryPath, $mode & 0777);
            }

            $syntax = $this->processRunner->run([$perlBinary, '-c', $temporaryPath], 20);
            if ($syntax['exit_code'] !== 0) {
                throw new RuntimeException('Perl rejected the generated configuration: ' . $this->redactRtspCredentials($syntax['output']));
            }

            $backupPath = $this->backup($path, $original);
            if (!rename($temporaryPath, $path)) {
                throw new RuntimeException('Unable to atomically replace streams.pl.');
            }
            $temporaryPath = '';

            $restarted = false;
            $restartOutput = '';
            if (!empty($settings['restart_on_publish'])) {
                $restart = $this->restartService(
                    (string)($settings['service_name'] ?? 'rtsp-streams.service'),
                    !empty($settings['use_sudo'])
                );
                $restarted = $restart['exit_code'] === 0;
                $restartOutput = $restart['output'];
            }

            return [
                'stream_count' => count($streams),
                'backup_path' => $backupPath,
                'syntax_output' => $this->redactRtspCredentials($syntax['output']),
                'restarted' => $restarted,
                'restart_output' => $restartOutput,
            ];
        } finally {
            if ($temporaryPath !== '' && is_file($temporaryPath)) {
                @unlink($temporaryPath);
            }
            flock($lock, LOCK_UN);
            fclose($lock);
        }
    }

    public function merge(string $source, string $block, array $streams): string
    {
        $withoutManagedBlock = $source;
        $begin = strpos($source, self::BEGIN_MARKER);
        $end = strpos($source, self::END_MARKER);
        if (substr_count($source, self::BEGIN_MARKER) > 1 || substr_count($source, self::END_MARKER) > 1) {
            throw new RuntimeException('Duplicate Camera Manager marker blocks were found in streams.pl.');
        }
        if (($begin === false) !== ($end === false) || ($begin !== false && $end < $begin)) {
            throw new RuntimeException('The managed marker block in streams.pl is incomplete.');
        }

        if ($begin !== false) {
            $lineStart = strrpos(substr($source, 0, $begin), "\n");
            $lineStart = $lineStart === false ? 0 : $lineStart + 1;
            $lineEnd = strpos($source, "\n", $end);
            $lineEnd = $lineEnd === false ? strlen($source) : $lineEnd;
            $withoutManagedBlock = substr($source, 0, $lineStart) . substr($source, $lineEnd + ($lineEnd < strlen($source) ? 1 : 0));
        }

        foreach ($streams as $stream) {
            $key = preg_quote((string)$stream['stream_key'], '~');
            if (preg_match("~['\"]{$key}['\"]\\s*=>~", $withoutManagedBlock) === 1) {
                throw new RuntimeException('Stream key already exists outside the managed block: ' . $stream['stream_key']);
            }
        }

        if ($begin !== false) {
            return substr($source, 0, $lineStart) . $block . "\n" . substr($source, $lineEnd + ($lineEnd < strlen($source) ? 1 : 0));
        }

        if (preg_match('/%cam\s*=\s*\(/', $source, $open, PREG_OFFSET_CAPTURE) !== 1) {
            throw new RuntimeException('The %cam hash was not found in streams.pl.');
        }
        $searchOffset = $open[0][1] + strlen($open[0][0]);
        if (preg_match('/^\s*\);\s*$/m', $source, $close, PREG_OFFSET_CAPTURE, $searchOffset) !== 1) {
            throw new RuntimeException('The closing line of the %cam hash was not found.');
        }
        $insertAt = $close[0][1];
        $prefix = substr($source, 0, $insertAt);
        if ($prefix !== '' && !str_ends_with($prefix, "\n")) {
            $prefix .= "\n";
        }

        return $prefix . $block . "\n" . substr($source, $insertAt);
    }

    private function backup(string $path, string $contents): string
    {
        $directory = dirname($path) . '/.fireball-camera-manager-backups';
        if (!is_dir($directory) && !mkdir($directory, 0750, true) && !is_dir($directory)) {
            throw new RuntimeException('Unable to create the streams.pl backup directory.');
        }
        $backupPath = $directory . '/streams.pl.' . date('Ymd-His') . '.' . substr(hash('sha256', $contents), 0, 12) . '.bak';
        if (file_put_contents($backupPath, $contents, LOCK_EX) === false) {
            throw new RuntimeException('Unable to create a streams.pl backup.');
        }
        @chmod($backupPath, 0640);

        return $backupPath;
    }

    /** @return array{exit_code:int, output:string} */
    private function restartService(string $serviceName, bool $useSudo): array
    {
        if (!preg_match('/^[a-zA-Z0-9_.@-]{1,128}\.service$/', $serviceName)) {
            throw new RuntimeException('Invalid systemd service name.');
        }
        $systemctl = is_executable('/bin/systemctl') ? '/bin/systemctl' : '/usr/bin/systemctl';
        $command = [$systemctl, 'restart', $serviceName];
        if ($useSudo) {
            array_unshift($command, '-n');
            array_unshift($command, '/usr/bin/sudo');
        }

        return $this->processRunner->run($command, 30);
    }

    private function validatedStreamsPath(string $path): string
    {
        if ($path === '' || $path[0] !== '/' || basename($path) !== 'streams.pl') {
            throw new RuntimeException('streams.pl must be configured with an absolute path.');
        }
        if (is_link($path) || !is_file($path) || !is_readable($path) || !is_writable($path)) {
            throw new RuntimeException('streams.pl must be a readable, writable, regular file (not a symlink).');
        }

        return $path;
    }

    private function validatedBinary(string $path, string $name): string
    {
        if ($path === '' || $path[0] !== '/' || !is_file($path) || !is_executable($path)) {
            throw new RuntimeException('The configured ' . $name . ' binary is not executable.');
        }

        return $path;
    }

    private function perlSingleQuoted(string $value): string
    {
        return str_replace(['\\', "'"], ['\\\\', "\\'"], $value);
    }

    private function redactRtspCredentials(string $value): string
    {
        return preg_replace('~(rtsp://)[^\s@]+@~i', '$1***:***@', $value) ?? $value;
    }
}
