-- Shared by installation and demo reset. Parameters: now, creator_id, base_path.
-- No test accounts, requests, subscriptions, chat messages or fabricated analytics.
INSERT INTO post_categories (name, name_ru, name_en, slug, seo_title, seo_description, seo_keywords, seo_image, created_at)
VALUES
('Начало работы', 'Начало работы', 'Getting started', 'demo', 'Знакомство с FIREBALL CMS', 'Первые шаги, возможности CMS и подготовка сайта к публикации.', 'fireball cms, начало работы, запуск сайта', '', :now),
('Практические руководства', 'Практические руководства', 'Practical guides', 'guides', 'Руководства FIREBALL CMS', 'Работа с редактором, аккаунтом, медиа и уведомлениями.', 'fireball cms, редактор, руководства', '', :now),
('Идеи для сайта', 'Идеи для сайта', 'Website ideas', 'ideas', 'Идеи для вашего сайта', 'Примеры разделов и подходов для корпоративного сайта, блога и сообщества.', 'fireball cms, идеи, контент', '', :now)
ON DUPLICATE KEY UPDATE name = VALUES(name), name_ru = VALUES(name_ru), name_en = VALUES(name_en), seo_title = VALUES(seo_title), seo_description = VALUES(seo_description), seo_keywords = VALUES(seo_keywords);

INSERT INTO posts (title, slug, category, category_id, excerpt, content, image, seo_title, seo_description, seo_keywords, seo_image, hide_placeholder_image, show_on_home, priority, author_id, author_name, author_role, views_count, published_at, is_published)
SELECT 'Добро пожаловать в FIREBALL CMS', 'welcome-to-fireball-cms', category.name, category.id,
'Познакомьтесь с публикациями, страницами и личным кабинетом на примере готового демонстрационного сайта.',
REPLACE('<p>Этот сайт — отправная точка для вашего проекта. Здесь уже есть несколько категорий, публикации, информационные страницы и один черновик. Откройте материалы в админ-панели, посмотрите, как они устроены, и замените их своими.</p>
<div class="alert alert-info" role="alert"><strong>Это демонстрационный контент.</strong> Иллюстрации и тексты служат примерами. Перед запуском удалите ненужные материалы и настройте сайт под свой проект.</div>
<h2>Что попробовать первым</h2><ol><li>Откройте раздел «Записи» и отредактируйте заголовок, обложку и описание этой публикации.</li><li>Перейдите в «Страницы»: поменяйте текст и расположение ссылок в меню.</li><li>Загрузите собственные файлы через файловый менеджер и выберите их в редакторе.</li><li>Откройте профиль, проверьте настройки аккаунта и добавьте понравившуюся запись в избранное.</li></ol>
<h2>Что входит в демо</h2><p>В руководствах показаны работа с блочным редактором, галерея изображений, таблица, FAQ и чек-лист. Раздел «Идеи для сайта» поможет выбрать структуру проекта. Счётчики просмотров начинаются с нуля: демо не добавляет вымышленных посетителей.</p>
<p><a href="{{base_path}}/features">Посмотреть возможности</a> · <a href="{{base_path}}/demo-launch-guide">Памятка перед запуском</a></p>', '{{base_path}}', :base_path),
'assets/default/images/demo/workspace.svg', 'Добро пожаловать в FIREBALL CMS', 'Готовые примеры публикаций и страниц для знакомства с FIREBALL CMS.', 'fireball cms, демо, возможности', 'assets/default/images/demo/workspace.svg', 0, 1, 100, author.id, COALESCE(NULLIF(TRIM(author.name), ''), 'Creator'), 'creator', 0, :now, 1
FROM post_categories category JOIN users author ON author.id = :creator_id AND author.role = 'creator' WHERE category.slug = 'demo'
ON DUPLICATE KEY UPDATE title = VALUES(title), category = VALUES(category), category_id = VALUES(category_id), excerpt = VALUES(excerpt), content = VALUES(content), image = VALUES(image), seo_title = VALUES(seo_title), seo_description = VALUES(seo_description), seo_keywords = VALUES(seo_keywords), seo_image = VALUES(seo_image), hide_placeholder_image = VALUES(hide_placeholder_image), show_on_home = VALUES(show_on_home), priority = VALUES(priority), author_id = VALUES(author_id), author_name = VALUES(author_name), author_role = VALUES(author_role), published_at = VALUES(published_at), is_published = VALUES(is_published);

INSERT INTO posts (title, slug, category, category_id, excerpt, content, image, seo_title, seo_description, seo_keywords, seo_image, hide_placeholder_image, show_on_home, priority, author_id, author_name, author_role, views_count, published_at, is_published)
SELECT 'Первая публикация: от идеи до готовой записи', 'first-publication', category.name, category.id,
'Заголовок, краткое описание, категория и обложка: простой порядок подготовки материала к публикации.',
REPLACE('<p>Хорошая запись отвечает на один понятный вопрос читателя. Начните с идеи, а оформление добавляйте по мере необходимости — так проще сделать материал полезным и аккуратным.</p>
<h2>Подготовьте основу</h2><ol><li><strong>Заголовок.</strong> Коротко сформулируйте тему, без общих обещаний.</li><li><strong>Описание.</strong> Расскажите в одном-двух предложениях, что читатель узнает.</li><li><strong>Категория.</strong> Выберите раздел, в котором посетитель ожидает найти этот материал.</li><li><strong>Обложка.</strong> Используйте изображение с правом публикации и проверьте его кадрирование.</li></ol>
<h2>Соберите содержание</h2><p>Разделите длинный текст подзаголовками. Для шагов используйте нумерованный список, для сравнения — таблицу. Изображению добавьте осмысленный альтернативный текст, а ссылке — понятное название.</p>
<blockquote>Одна публикация — одна основная мысль. Всё остальное помогает её объяснить.</blockquote>
<h2>Проверьте перед публикацией</h2><ul><li>Заголовок и описание хорошо смотрятся в списке записей.</li><li>Ссылки ведут на существующие страницы.</li><li>Изображения не растягиваются на телефоне.</li><li>Дата публикации и состояние записи выбраны правильно.</li></ul><p>Если материал ещё не готов, оставьте его черновиком. Пример черновика уже есть в админ-панели.</p>', '{{base_path}}', :base_path),
'assets/default/images/demo/content.svg', 'Как подготовить первую публикацию', 'Практический порядок создания записи: текст, обложка, категория и проверка перед публикацией.', 'публикации, контент, редактор', 'assets/default/images/demo/content.svg', 0, 1, 90, author.id, COALESCE(NULLIF(TRIM(author.name), ''), 'Creator'), 'creator', 0, DATE_SUB(:now, INTERVAL 1 DAY), 1
FROM post_categories category JOIN users author ON author.id = :creator_id AND author.role = 'creator' WHERE category.slug = 'guides'
ON DUPLICATE KEY UPDATE title = VALUES(title), category = VALUES(category), category_id = VALUES(category_id), excerpt = VALUES(excerpt), content = VALUES(content), image = VALUES(image), seo_title = VALUES(seo_title), seo_description = VALUES(seo_description), seo_keywords = VALUES(seo_keywords), seo_image = VALUES(seo_image), hide_placeholder_image = VALUES(hide_placeholder_image), show_on_home = VALUES(show_on_home), priority = VALUES(priority), author_id = VALUES(author_id), author_name = VALUES(author_name), author_role = VALUES(author_role), published_at = VALUES(published_at), is_published = VALUES(is_published);

INSERT INTO posts (title, slug, category, category_id, excerpt, content, image, seo_title, seo_description, seo_keywords, seo_image, hide_placeholder_image, show_on_home, priority, author_id, author_name, author_role, views_count, published_at, is_published)
SELECT 'Блочный редактор: галерея, таблица и ответы на вопросы', 'block-editor-examples', category.name, category.id,
'Посмотрите готовые примеры блоков и откройте запись в редакторе, чтобы настроить их под свой материал.',
REPLACE('{"version":2,"blocks":[
{"id":"demo-blocks-intro","type":"text","data":{"html":"<p>Блоки помогают собрать материал из понятных частей. Этот пример показывает изображения, таблицу и вопросы с раскрывающимися ответами. Оформление использует текущий шаблон CMS.</p>"}},
{"id":"demo-gallery-heading","type":"heading","data":{"level":"h2","html":"Галерея изображений"}},
{"id":"demo-gallery-intro","type":"text","data":{"html":"<p>Нажмите на иллюстрацию: изображения этой галереи можно переключать в общем окне просмотра. Замените их собственными файлами из файлового менеджера.</p>"}},
{"id":"demo-gallery","type":"gallery","data":{"items":[{"src":"{{base_path}}/assets/default/images/demo/workspace.svg","alt":"Демонстрационная иллюстрация рабочего пространства","caption":"Рабочее пространство проекта"},{"src":"{{base_path}}/assets/default/images/demo/content.svg","alt":"Демонстрационная иллюстрация структуры публикации","caption":"Материалы и публикации"},{"src":"{{base_path}}/assets/default/images/demo/community.svg","alt":"Демонстрационная иллюстрация общения с аудиторией","caption":"Аккаунт и сообщество"}]}},
{"id":"demo-table-heading","type":"heading","data":{"level":"h2","html":"Таблица для сравнения"}},
{"id":"demo-table","type":"table","data":{"header":true,"bordered":true,"responsive":true,"rows":[["Блок","Когда использовать","Что проверить"],["Галерея","Несколько связанных изображений","Порядок, подписи и альтернативный текст"],["Таблица","Сравнение характеристик или этапов","Читаемость на небольшом экране"],["FAQ","Короткие ответы на повторяющиеся вопросы","Понятные заголовки вопросов"]]}},
{"id":"demo-faq-heading","type":"heading","data":{"level":"h2","html":"Частые вопросы"}},
{"id":"demo-blocks-faq","type":"faq","data":{"items":[{"question":"Нужно ли знать HTML?","answer":"<p>Для обычного текста, списков, изображений и других готовых блоков HTML не требуется. Выбирайте блок и меняйте его содержимое в редакторе.</p>"},{"question":"Как изменить порядок изображений?","answer":"<p>Откройте настройки галереи, переставьте изображения и сохраните запись. Затем проверьте порядок на публичной странице.</p>"},{"question":"Можно ли взять уже загруженный файл?","answer":"<p>Да. Используйте выбор из файлового менеджера там, где он доступен в настройках блока, вместо повторной загрузки с компьютера.</p>"}]}}
]}', '{{base_path}}', :base_path),
'assets/default/images/demo/content.svg', 'Примеры блоков FIREBALL CMS', 'Галерея изображений, адаптивная таблица и FAQ в одной демонстрационной публикации.', 'блочный редактор, галерея, таблица, faq', 'assets/default/images/demo/content.svg', 0, 1, 80, author.id, COALESCE(NULLIF(TRIM(author.name), ''), 'Creator'), 'creator', 0, DATE_SUB(:now, INTERVAL 2 DAY), 1
FROM post_categories category JOIN users author ON author.id = :creator_id AND author.role = 'creator' WHERE category.slug = 'guides'
ON DUPLICATE KEY UPDATE title = VALUES(title), category = VALUES(category), category_id = VALUES(category_id), excerpt = VALUES(excerpt), content = VALUES(content), image = VALUES(image), seo_title = VALUES(seo_title), seo_description = VALUES(seo_description), seo_keywords = VALUES(seo_keywords), seo_image = VALUES(seo_image), hide_placeholder_image = VALUES(hide_placeholder_image), show_on_home = VALUES(show_on_home), priority = VALUES(priority), author_id = VALUES(author_id), author_name = VALUES(author_name), author_role = VALUES(author_role), published_at = VALUES(published_at), is_published = VALUES(is_published);

INSERT INTO posts (title, slug, category, category_id, excerpt, content, image, seo_title, seo_description, seo_keywords, seo_image, hide_placeholder_image, show_on_home, priority, author_id, author_name, author_role, views_count, published_at, is_published)
SELECT 'Личный кабинет: профиль, избранное и безопасность', 'account-and-security', category.name, category.id,
'Разделы аккаунта помогают настроить профиль, сохранить полезные записи и проверить устройства и сессии.',
REPLACE('<p>Личный кабинет объединяет настройки аккаунта и персональные разделы сайта. Их состав зависит от установленных плагинов и доступных возможностей.</p>
<h2>Профиль и аватар</h2><p>Укажите имя, которое увидят другие пользователи, и загрузите аватар. После сохранения проверьте, как изображение выглядит в навигации и в карточке профиля.</p>
<h2>Избранное</h2><p>Нажмите на сердечко у записи, чтобы сохранить её. Добавленные материалы доступны в разделе «Избранное»; повторное нажатие убирает запись из списка.</p>
<h2>Устройства и сессии</h2><p>Периодически проверяйте список входов. Если обнаружили незнакомую сессию, завершите её и смените пароль. Не используйте один пароль для разных сервисов.</p>
<h2>Безопасность аккаунта</h2><ul><li>Выберите длинный уникальный пароль.</li><li>Если двухфакторная аутентификация доступна, включите её в настройках безопасности.</li><li>Проверьте актуальность почты для восстановления доступа.</li><li>На чужом устройстве обязательно выйдите из аккаунта.</li></ul><p><a href="{{base_path}}/profile">Открыть личный кабинет</a></p>', '{{base_path}}', :base_path),
'assets/default/images/demo/community.svg', 'Личный кабинет FIREBALL CMS', 'Профиль, избранные записи, устройства и основные настройки безопасности аккаунта.', 'профиль, избранное, устройства, безопасность', 'assets/default/images/demo/community.svg', 0, 1, 70, author.id, COALESCE(NULLIF(TRIM(author.name), ''), 'Creator'), 'creator', 0, DATE_SUB(:now, INTERVAL 3 DAY), 1
FROM post_categories category JOIN users author ON author.id = :creator_id AND author.role = 'creator' WHERE category.slug = 'guides'
ON DUPLICATE KEY UPDATE title = VALUES(title), category = VALUES(category), category_id = VALUES(category_id), excerpt = VALUES(excerpt), content = VALUES(content), image = VALUES(image), seo_title = VALUES(seo_title), seo_description = VALUES(seo_description), seo_keywords = VALUES(seo_keywords), seo_image = VALUES(seo_image), hide_placeholder_image = VALUES(hide_placeholder_image), show_on_home = VALUES(show_on_home), priority = VALUES(priority), author_id = VALUES(author_id), author_name = VALUES(author_name), author_role = VALUES(author_role), published_at = VALUES(published_at), is_published = VALUES(is_published);

INSERT INTO posts (title, slug, category, category_id, excerpt, content, image, seo_title, seo_description, seo_keywords, seo_image, hide_placeholder_image, show_on_home, priority, author_id, author_name, author_role, views_count, published_at, is_published)
SELECT 'PWA и уведомления: что проверить на своём устройстве', 'pwa-and-notifications', category.name, category.id,
'Как проверить установку сайта, разрешение на уведомления и привязку устройства без вымышленных тестовых пушей.',
REPLACE('<p>Если владелец сайта настроил PWA, сайт можно открывать как установленное приложение. Наличие установки и возможность Push-уведомлений зависят от браузера, устройства и настроек сайта.</p>
<h2>Проверка по шагам</h2><ol><li>Откройте сайт и найдите доступную в браузере команду установки или добавления на главный экран.</li><li>Запустите установленное приложение и войдите в аккаунт.</li><li>Откройте настройки уведомлений в личном кабинете.</li><li>Разрешите уведомления, если хотите их получать, и дождитесь результата проверки.</li><li>При изменении устройства или разрешений повторно проверьте статус.</li></ol>
<h2>Если уведомления не приходят</h2><ul><li>Проверьте разрешения браузера и системы.</li><li>Проверьте, включены ли уведомления для аккаунта.</li><li>Убедитесь, что устройство ещё привязано на сайте.</li><li>Попросите администратора проверить технический журнал отправок.</li></ul>
<div class="alert alert-secondary" role="alert">Технический статус отправки не равен подтверждению прочтения пользователем. Демо-набор не регистрирует устройства и не отправляет уведомления.</div>', '{{base_path}}', :base_path),
'assets/default/images/demo/community.svg', 'PWA и уведомления на вашем устройстве', 'Проверка установки PWA, разрешений уведомлений и состояния привязанного устройства.', 'pwa, уведомления, устройства', 'assets/default/images/demo/community.svg', 0, 1, 60, author.id, COALESCE(NULLIF(TRIM(author.name), ''), 'Creator'), 'creator', 0, DATE_SUB(:now, INTERVAL 4 DAY), 1
FROM post_categories category JOIN users author ON author.id = :creator_id AND author.role = 'creator' WHERE category.slug = 'guides'
ON DUPLICATE KEY UPDATE title = VALUES(title), category = VALUES(category), category_id = VALUES(category_id), excerpt = VALUES(excerpt), content = VALUES(content), image = VALUES(image), seo_title = VALUES(seo_title), seo_description = VALUES(seo_description), seo_keywords = VALUES(seo_keywords), seo_image = VALUES(seo_image), hide_placeholder_image = VALUES(hide_placeholder_image), show_on_home = VALUES(show_on_home), priority = VALUES(priority), author_id = VALUES(author_id), author_name = VALUES(author_name), author_role = VALUES(author_role), published_at = VALUES(published_at), is_published = VALUES(is_published);

INSERT INTO posts (title, slug, category, category_id, excerpt, content, image, seo_title, seo_description, seo_keywords, seo_image, hide_placeholder_image, show_on_home, priority, author_id, author_name, author_role, views_count, published_at, is_published)
SELECT 'Чек-лист перед запуском сайта', 'site-launch-checklist', category.name, category.id,
'Настройки, контент, доступы и проверка на телефоне — список того, что стоит пройти перед открытием сайта.',
REPLACE('{"version":2,"blocks":[
{"id":"demo-checklist-intro","type":"text","data":{"html":"<p>Перед запуском пройдите сайт глазами посетителя. Этот список — пример блока чек-листа: в редакторе его можно дополнить задачами своего проекта.</p>"}},
{"id":"demo-checklist","type":"checklist","data":{"items":[{"text":"Заменить название, описание и логотип сайта.","checked":false},{"text":"Удалить или переработать демонстрационные материалы.","checked":false},{"text":"Проверить обложки, подписи и ссылки в публикациях.","checked":false},{"text":"Настроить страницы и ссылки в верхнем и нижнем меню.","checked":false},{"text":"Проверить вход, восстановление доступа и отправку писем после настройки почты.","checked":false},{"text":"Проверить роли команды и включённые плагины.","checked":false},{"text":"Создать резервную копию и проверить порядок восстановления.","checked":false},{"text":"Открыть сайт на телефоне и компьютере, проверить поиск и галерею.","checked":false}]}},
{"id":"demo-checklist-heading","type":"heading","data":{"level":"h2","html":"Не забудьте про демонстрационные данные"}},
{"id":"demo-checklist-note","type":"text","data":{"html":"<p>Демо — учебный набор, а не готовые сведения о вашей компании. Не публикуйте примеры как реальные обещания, статистику или условия услуг. Наполните страницы актуальными данными своего проекта.</p>"}},
{"id":"demo-checklist-link","type":"text","data":{"html":"<p><a href={{base_path}}/demo-launch-guide>Открыть подробную памятку</a></p>"}}
]}', '{{base_path}}', :base_path),
'assets/default/images/demo/workspace.svg', 'Чек-лист запуска сайта на FIREBALL CMS', 'Проверьте контент, настройки, доступы, резервную копию и отображение сайта перед запуском.', 'запуск сайта, чек-лист, настройки', 'assets/default/images/demo/workspace.svg', 0, 1, 50, author.id, COALESCE(NULLIF(TRIM(author.name), ''), 'Creator'), 'creator', 0, DATE_SUB(:now, INTERVAL 5 DAY), 1
FROM post_categories category JOIN users author ON author.id = :creator_id AND author.role = 'creator' WHERE category.slug = 'demo'
ON DUPLICATE KEY UPDATE title = VALUES(title), category = VALUES(category), category_id = VALUES(category_id), excerpt = VALUES(excerpt), content = VALUES(content), image = VALUES(image), seo_title = VALUES(seo_title), seo_description = VALUES(seo_description), seo_keywords = VALUES(seo_keywords), seo_image = VALUES(seo_image), hide_placeholder_image = VALUES(hide_placeholder_image), show_on_home = VALUES(show_on_home), priority = VALUES(priority), author_id = VALUES(author_id), author_name = VALUES(author_name), author_role = VALUES(author_role), published_at = VALUES(published_at), is_published = VALUES(is_published);

INSERT INTO posts (title, slug, category, category_id, excerpt, content, image, seo_title, seo_description, seo_keywords, seo_image, hide_placeholder_image, show_on_home, priority, author_id, author_name, author_role, views_count, published_at, is_published)
SELECT 'Три сценария для вашего следующего сайта', 'website-ideas', category.name, category.id,
'Корпоративный сайт, тематический блог или сообщество: начните с задач аудитории и подберите подходящие разделы.',
REPLACE('<p>Универсальная CMS полезна там, где проект растёт постепенно. Начните с нескольких понятных разделов, а дополнительные возможности подключайте тогда, когда появится реальная задача.</p>
<h2>1. Сайт команды или небольшой компании</h2><p>Опубликуйте информацию о проекте, новости и ответы на частые вопросы. Добавьте контакты и понятный способ обратиться к вам. Галерея поможет показать работы или события.</p>
<h2>2. Тематический блог</h2><p>Разделите публикации по темам, задайте регулярный формат и добавляйте связанные материалы. Избранное поможет читателям возвращаться к полезным записям.</p>
<h2>3. Сообщество или сервисный проект</h2><p>Начните с личного кабинета и полезных материалов. Если нужны календарь, подписки, медиатека или другие функции, изучите соответствующие плагины и настройте их отдельно.</p>
<h2>Как выбрать</h2><p>Запишите, кто ваш посетитель, что он должен узнать и какое действие выполнить. По этим трём вопросам проще подобрать структуру меню, набор страниц и первые публикации.</p>
<blockquote>Добавляйте раздел не потому, что он есть в CMS, а потому, что он помогает пользователю.</blockquote>', '{{base_path}}', :base_path),
'assets/default/images/demo/workspace.svg', 'Идеи для сайта на FIREBALL CMS', 'Сценарии корпоративного сайта, блога и сообщества с понятной структурой контента.', 'идеи для сайта, блог, сообщество', 'assets/default/images/demo/workspace.svg', 0, 0, 40, author.id, COALESCE(NULLIF(TRIM(author.name), ''), 'Creator'), 'creator', 0, DATE_SUB(:now, INTERVAL 6 DAY), 1
FROM post_categories category JOIN users author ON author.id = :creator_id AND author.role = 'creator' WHERE category.slug = 'ideas'
ON DUPLICATE KEY UPDATE title = VALUES(title), category = VALUES(category), category_id = VALUES(category_id), excerpt = VALUES(excerpt), content = VALUES(content), image = VALUES(image), seo_title = VALUES(seo_title), seo_description = VALUES(seo_description), seo_keywords = VALUES(seo_keywords), seo_image = VALUES(seo_image), hide_placeholder_image = VALUES(hide_placeholder_image), show_on_home = VALUES(show_on_home), priority = VALUES(priority), author_id = VALUES(author_id), author_name = VALUES(author_name), author_role = VALUES(author_role), published_at = VALUES(published_at), is_published = VALUES(is_published);

INSERT INTO posts (title, slug, category, category_id, excerpt, content, image, seo_title, seo_description, seo_keywords, seo_image, hide_placeholder_image, show_on_home, priority, author_id, author_name, author_role, views_count, published_at, is_published)
SELECT 'Черновик: план следующей публикации', 'demo-draft', category.name, category.id,
'Непубличный пример черновика. Дополните план, проверьте содержание и опубликуйте, когда материал будет готов.',
'<p>Эта запись сохранена как черновик и не показывается посетителям сайта. Используйте её, чтобы попробовать редактор, предварительный просмотр и публикацию.</p><h2>План материала</h2><ol><li>Сформулировать вопрос читателя.</li><li>Подготовить короткий ответ и примеры.</li><li>Добавить изображение и проверить ссылки.</li><li>Отредактировать заголовок и описание.</li><li>Посмотреть материал на телефоне и опубликовать.</li></ol><p><strong>Заметка редактору:</strong> замените этот текст реальным содержанием перед включением публикации.</p>',
'assets/default/images/demo/content.svg', 'План следующей публикации', 'Демонстрационный черновик для знакомства с редактором и проверкой публикации.', 'черновик, редактор, план', '', 0, 0, 0, author.id, COALESCE(NULLIF(TRIM(author.name), ''), 'Creator'), 'creator', 0, :now, 0
FROM post_categories category JOIN users author ON author.id = :creator_id AND author.role = 'creator' WHERE category.slug = 'ideas'
ON DUPLICATE KEY UPDATE title = VALUES(title), category = VALUES(category), category_id = VALUES(category_id), excerpt = VALUES(excerpt), content = VALUES(content), image = VALUES(image), seo_title = VALUES(seo_title), seo_description = VALUES(seo_description), seo_keywords = VALUES(seo_keywords), seo_image = VALUES(seo_image), hide_placeholder_image = VALUES(hide_placeholder_image), show_on_home = VALUES(show_on_home), priority = VALUES(priority), author_id = VALUES(author_id), author_name = VALUES(author_name), author_role = VALUES(author_role), published_at = VALUES(published_at), is_published = VALUES(is_published);

INSERT INTO pages (title, menu_title, slug, content, meta_title, meta_description, is_published, show_in_header, show_in_footer, show_in_legal_information, menu_order, created_at, updated_at)
VALUES ('О демонстрационном сайте', 'О проекте', 'about-demo',
REPLACE('<p>Это демонстрационный сайт на FIREBALL CMS. Его задача — показать, как устроены публикации, страницы, личный кабинет и работа с контентом в текущем шаблоне.</p><h2>Что вы здесь найдёте</h2><ul><li>Три категории публикаций с содержательными примерами.</li><li>Галерею изображений, таблицу, FAQ и чек-лист.</li><li>Страницы с навигацией и отдельный пример черновика в админ-панели.</li></ul><h2>Как использовать этот пример</h2><p>Сохраните понравившуюся структуру, замените тексты и иллюстрации и удалите лишние страницы. Демо не создаёт тестовые аккаунты, заявки, сообщения, платежи или подключения к внешним сервисам.</p><p><a href="{{base_path}}/posts">Открыть публикации</a> · <a href="{{base_path}}/features">Возможности CMS</a></p>', '{{base_path}}', :base_path),
'О демонстрационном сайте FIREBALL CMS', 'Знакомство с примером сайта: публикации, страницы, редактор и настройки.', 1, 1, 1, 0, 10, :now, :now)
ON DUPLICATE KEY UPDATE title = VALUES(title), menu_title = VALUES(menu_title), content = VALUES(content), meta_title = VALUES(meta_title), meta_description = VALUES(meta_description), is_published = VALUES(is_published), show_in_header = VALUES(show_in_header), show_in_footer = VALUES(show_in_footer), show_in_legal_information = VALUES(show_in_legal_information), menu_order = VALUES(menu_order), updated_at = VALUES(updated_at);

INSERT INTO pages (title, menu_title, slug, content, meta_title, meta_description, is_published, show_in_header, show_in_footer, show_in_legal_information, menu_order, created_at, updated_at)
VALUES ('Возможности FIREBALL CMS', 'Возможности', 'features',
REPLACE('<p>FIREBALL CMS объединяет публикации, информационные страницы и инструменты администрирования. Этот обзор описывает примеры из демо, а не условия обслуживания или обещания конкретного проекта.</p><h2>Контент и редактор</h2><p>Создавайте записи и страницы, распределяйте публикации по категориям, настраивайте описания и обложки. Блочный редактор помогает собирать текст, списки, изображения, галереи, таблицы и ответы на вопросы.</p><h2>Файлы и медиа</h2><p>Файловый менеджер позволяет выбирать уже загруженные материалы и организовывать их по папкам. Служебные и используемые файлы защищены от недоступных действий.</p><h2>Аккаунт и навигация</h2><p>Посетители могут пользоваться настройками профиля и избранными записями. Доступные разделы личного кабинета зависят от конфигурации сайта и установленных плагинов.</p><h2>Администрирование</h2><p>В панели управления доступны аналитика посещений, роли команды, настройки сайта и обслуживание системы. Возможности плагинов, почты и Push-уведомлений требуют отдельной настройки.</p><p><a href="{{base_path}}/posts/block-editor-examples">Посмотреть пример блоков</a></p>', '{{base_path}}', :base_path),
'Возможности FIREBALL CMS', 'Публикации, страницы, блочный редактор, файлы, личный кабинет и администрирование.', 1, 1, 1, 0, 20, :now, :now)
ON DUPLICATE KEY UPDATE title = VALUES(title), menu_title = VALUES(menu_title), content = VALUES(content), meta_title = VALUES(meta_title), meta_description = VALUES(meta_description), is_published = VALUES(is_published), show_in_header = VALUES(show_in_header), show_in_footer = VALUES(show_in_footer), show_in_legal_information = VALUES(show_in_legal_information), menu_order = VALUES(menu_order), updated_at = VALUES(updated_at);

INSERT INTO pages (title, menu_title, slug, content, meta_title, meta_description, is_published, show_in_header, show_in_footer, show_in_legal_information, menu_order, created_at, updated_at)
VALUES ('Частые вопросы о демо', 'Вопросы и ответы', 'demo-faq',
REPLACE('{"version":2,"blocks":[
{"id":"demo-faq-intro","type":"text","data":{"html":"<p>Короткие ответы для знакомства с демонстрационным сайтом. Замените их вопросами вашей аудитории перед запуском.</p>"}},
{"id":"demo-page-faq","type":"faq","data":{"items":[{"question":"Где изменить эти страницы?","answer":"<p>В разделе «Страницы» админ-панели. Там можно отредактировать содержание, название ссылки и её расположение в меню.</p>"},{"question":"Все записи опубликованы?","answer":"<p>Семь записей доступны посетителям, а одна оставлена черновиком для проверки процесса редактирования и публикации.</p>"},{"question":"Можно ли удалить демо-контент?","answer":"<p>Да. Удалите ненужные примеры через админ-панель или замените их своим содержанием. Полный сброс CMS — отдельное разрушительное действие с резервной копией и подтверждением.</p>"},{"question":"Плагины уже настроены?","answer":"<p>Нет. Демо не создаёт тарифы, подписки, серверы или другие внешние подключения. Установленные плагины настраиваются отдельно.</p>"},{"question":"Почему у записей нет просмотров?","answer":"<p>Демо не подставляет вымышленные показатели. Просмотры и аналитика собираются при реальном использовании сайта.</p>"},{"question":"Это готовые юридические документы?","answer":"<p>Нет. Тексты демонстрационные. Документы и сведения, необходимые вашему проекту, подготовьте отдельно.</p>"}]}},
{"id":"demo-faq-link","type":"text","data":{"html":"<p><a href={{base_path}}/contacts>Перейти к форме обращения</a></p>"}}
]}', '{{base_path}}', :base_path),
'Ответы на вопросы о демо FIREBALL CMS', 'Как редактировать демо, публиковать черновики и подготовить сайт к работе.', 1, 1, 1, 0, 30, :now, :now)
ON DUPLICATE KEY UPDATE title = VALUES(title), menu_title = VALUES(menu_title), content = VALUES(content), meta_title = VALUES(meta_title), meta_description = VALUES(meta_description), is_published = VALUES(is_published), show_in_header = VALUES(show_in_header), show_in_footer = VALUES(show_in_footer), show_in_legal_information = VALUES(show_in_legal_information), menu_order = VALUES(menu_order), updated_at = VALUES(updated_at);

INSERT INTO pages (title, menu_title, slug, content, meta_title, meta_description, is_published, show_in_header, show_in_footer, show_in_legal_information, menu_order, created_at, updated_at)
VALUES ('Памятка владельцу перед запуском', 'Памятка по запуску', 'demo-launch-guide',
REPLACE('<p>Этот материал помогает превратить демонстрационную установку в собственный сайт. В нём нет автоматических настроек: каждый пункт нужно проверить в вашем окружении.</p><h2>1. Содержание и внешний вид</h2><ul><li>Название, описание, логотип и иконки сайта соответствуют вашему проекту.</li><li>Демонстрационные тексты и обложки заменены.</li><li>Меню короткое и ведёт на нужные разделы.</li><li>Страницы корректно читаются на телефоне и компьютере.</li></ul><h2>2. Аккаунты и доступы</h2><ul><li>Роли выдаются только необходимым участникам команды.</li><li>Пароль создателя уникален, настройки безопасности проверены.</li><li>Почта и восстановление доступа протестированы после настройки отправки писем.</li></ul><h2>3. Эксплуатация</h2><ul><li>Проверена резервная копия и порядок восстановления.</li><li>Плагины настроены, ненужные функции отключены.</li><li>Поиск, формы, галерея и разрешения уведомлений проверены.</li><li>Правила и документы сайта подготовлены под ваш проект, а не скопированы из демо.</li></ul><div class="alert alert-warning" role="alert">Не запускайте полный или демонстрационный сброс для удаления нескольких примеров: используйте обычное редактирование и удаление материалов.</div><p><a href="{{base_path}}/posts/site-launch-checklist">Открыть короткий чек-лист</a></p>', '{{base_path}}', :base_path),
'Памятка запуска сайта на FIREBALL CMS', 'Проверка контента, доступов, резервных копий, поиска и настроек перед запуском.', 1, 0, 1, 0, 40, :now, :now)
ON DUPLICATE KEY UPDATE title = VALUES(title), menu_title = VALUES(menu_title), content = VALUES(content), meta_title = VALUES(meta_title), meta_description = VALUES(meta_description), is_published = VALUES(is_published), show_in_header = VALUES(show_in_header), show_in_footer = VALUES(show_in_footer), show_in_legal_information = VALUES(show_in_legal_information), menu_order = VALUES(menu_order), updated_at = VALUES(updated_at);
