CREATE TABLE IF NOT EXISTS analytics_visits (
    id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
    session_id VARCHAR(128) NOT NULL,
    ip VARCHAR(45) NOT NULL,
    country VARCHAR(120) NULL,
    country_code VARCHAR(8) NULL,
    city VARCHAR(120) NULL,
    device_type VARCHAR(20) NOT NULL DEFAULT 'Desktop',
    os VARCHAR(40) NOT NULL DEFAULT 'Other',
    browser VARCHAR(40) NOT NULL DEFAULT 'Other',
    referer TEXT NULL,
    source VARCHAR(80) NOT NULL DEFAULT 'Direct',
    landing_page VARCHAR(2048) NOT NULL,
    current_page VARCHAR(2048) NOT NULL,
    utm_source VARCHAR(255) NULL,
    utm_medium VARCHAR(255) NULL,
    utm_campaign VARCHAR(255) NULL,
    utm_content VARCHAR(255) NULL,
    utm_term VARCHAR(255) NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_created_at (created_at),
    KEY idx_session_created (session_id, created_at),
    KEY idx_source_created (source, created_at),
    KEY idx_country_created (country_code, created_at),
    KEY idx_device_created (device_type, created_at),
    KEY idx_os_created (os, created_at),
    KEY idx_browser_created (browser, created_at),
    KEY idx_page_created (current_page(191), created_at),
    KEY idx_utm_source_created (utm_source(120), created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
