CREATE TABLE IF NOT EXISTS vpn_servers (
    id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    code VARCHAR(80) NOT NULL,
    country_code CHAR(2) NULL,
    country_name VARCHAR(120) NULL,
    flag_emoji VARCHAR(16) NULL,
    show_flag TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
    country VARCHAR(120) NULL,
    city VARCHAR(120) NULL,
    panel_url VARCHAR(500) NOT NULL,
    public_host VARCHAR(255) NULL,
    panel_path VARCHAR(190) NULL,
    api_auth_type VARCHAR(30) NOT NULL DEFAULT 'token',
    api_token_encrypted MEDIUMTEXT NULL,
    username_encrypted MEDIUMTEXT NULL,
    password_encrypted MEDIUMTEXT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'unchecked',
    is_enabled TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
    last_check_at DATETIME NULL,
    last_success_at DATETIME NULL,
    last_error TEXT NULL,
    sort_order INT(10) UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY code (code),
    KEY country_code (country_code),
    KEY status (status),
    KEY is_enabled (is_enabled),
    KEY sort_order (sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS vpn_inbounds (
    id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    server_id INT(10) UNSIGNED NOT NULL,
    remote_inbound_id VARCHAR(80) NULL,
    name VARCHAR(255) NOT NULL,
    protocol VARCHAR(80) NULL,
    remark VARCHAR(255) NULL,
    port INT(10) UNSIGNED NULL,
    is_enabled TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
    status VARCHAR(40) NOT NULL DEFAULT 'active',
    settings_json MEDIUMTEXT NULL,
    stream_settings_json MEDIUMTEXT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY server_remote_inbound (server_id, remote_inbound_id),
    KEY server_id (server_id),
    KEY remote_inbound_id (remote_inbound_id),
    KEY status (status),
    KEY is_enabled (is_enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS vpn_plans (
    id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    description TEXT NULL,
    duration_days INT(10) UNSIGNED NOT NULL DEFAULT 30,
    traffic_limit_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
    device_limit INT(10) UNSIGNED NOT NULL DEFAULT 1,
    is_active TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
    traffic_mode VARCHAR(30) NOT NULL DEFAULT 'shared',
    sort_order INT(10) UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY is_active (is_active),
    KEY traffic_mode (traffic_mode),
    KEY sort_order (sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS vpn_plan_servers (
    id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    plan_id INT(10) UNSIGNED NOT NULL,
    server_id INT(10) UNSIGNED NOT NULL,
    inbound_id INT(10) UNSIGNED NULL,
    sort_order INT(10) UNSIGNED NOT NULL DEFAULT 0,
    is_enabled TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY plan_server_inbound (plan_id, server_id, inbound_id),
    KEY plan_id (plan_id),
    KEY server_id (server_id),
    KEY inbound_id (inbound_id),
    KEY is_enabled (is_enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS vpn_subscriptions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id INT(10) UNSIGNED NOT NULL,
    plan_id INT(10) UNSIGNED NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'provisioning',
    traffic_mode VARCHAR(30) NOT NULL DEFAULT 'shared',
    traffic_limit_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
    traffic_used_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
    device_limit INT(10) UNSIGNED NOT NULL DEFAULT 1,
    starts_at DATETIME NULL,
    expires_at DATETIME NULL,
    created_by INT(10) UNSIGNED NULL,
    source VARCHAR(80) NULL,
    source_order_id VARCHAR(120) NULL,
    subscription_token VARCHAR(128) NULL,
    subscription_url VARCHAR(700) NULL,
    subscription_token_encrypted MEDIUMTEXT NULL,
    subscription_token_hash VARCHAR(128) NULL,
    subscription_token_preview VARCHAR(32) NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY user_id (user_id),
    KEY plan_id (plan_id),
    KEY status (status),
    KEY expires_at (expires_at),
    KEY source_order (source, source_order_id),
    KEY subscription_token (subscription_token),
    KEY subscription_token_hash (subscription_token_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS vpn_subscription_nodes (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    subscription_id BIGINT UNSIGNED NOT NULL,
    server_id INT(10) UNSIGNED NOT NULL,
    inbound_id INT(10) UNSIGNED NULL,
    remote_client_id VARCHAR(120) NULL,
    client_uuid VARCHAR(120) NULL,
    client_email VARCHAR(255) NULL,
    client_remark VARCHAR(255) NULL,
    subscription_item_name VARCHAR(255) NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'creating',
    traffic_limit_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
    traffic_used_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
    last_sync_at DATETIME NULL,
    last_error TEXT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY subscription_server_inbound (subscription_id, server_id, inbound_id),
    KEY subscription_id (subscription_id),
    KEY server_id (server_id),
    KEY inbound_id (inbound_id),
    KEY status (status),
    KEY client_email (client_email),
    CONSTRAINT fk_vpn_nodes_subscription FOREIGN KEY (subscription_id) REFERENCES vpn_subscriptions(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS vpn_remote_clients (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    server_id INT(10) UNSIGNED NOT NULL,
    inbound_id INT(10) UNSIGNED NULL,
    remote_inbound_id VARCHAR(80) NULL,
    remote_client_key VARCHAR(128) NOT NULL,
    client_uuid VARCHAR(120) NULL,
    client_email VARCHAR(255) NULL,
    client_remark VARCHAR(255) NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'active',
    traffic_limit_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
    traffic_used_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
    expires_at DATETIME NULL,
    raw_json MEDIUMTEXT NULL,
    last_seen_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY server_inbound_client (server_id, remote_inbound_id, remote_client_key),
    KEY server_id (server_id),
    KEY inbound_id (inbound_id),
    KEY client_email (client_email),
    KEY client_uuid (client_uuid),
    KEY status (status),
    KEY last_seen_at (last_seen_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS vpn_traffic_snapshots (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    subscription_id BIGINT UNSIGNED NULL,
    node_id BIGINT UNSIGNED NULL,
    server_id INT(10) UNSIGNED NULL,
    inbound_id INT(10) UNSIGNED NULL,
    upload_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
    download_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
    total_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
    traffic_used_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
    captured_at DATETIME NULL,
    recorded_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY subscription_id (subscription_id),
    KEY node_id (node_id),
    KEY server_id (server_id),
    KEY inbound_id (inbound_id),
    KEY captured_at (captured_at),
    KEY recorded_at (recorded_at),
    CONSTRAINT fk_vpn_traffic_subscription FOREIGN KEY (subscription_id) REFERENCES vpn_subscriptions(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS vpn_notifications (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    subscription_id BIGINT UNSIGNED NOT NULL,
    user_id INT(10) UNSIGNED NOT NULL,
    type VARCHAR(60) NOT NULL,
    scheduled_for DATE NULL,
    sent_at DATETIME NULL,
    channel VARCHAR(40) NOT NULL DEFAULT 'account',
    status VARCHAR(30) NOT NULL DEFAULT 'pending',
    error_message TEXT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY vpn_notification_once (subscription_id, type, scheduled_for, channel),
    KEY user_id (user_id),
    KEY type (type),
    KEY status (status),
    KEY scheduled_for (scheduled_for),
    CONSTRAINT fk_vpn_notifications_subscription FOREIGN KEY (subscription_id) REFERENCES vpn_subscriptions(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS vpn_events (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    event_type VARCHAR(120) NOT NULL,
    user_id INT(10) UNSIGNED NULL,
    admin_id INT(10) UNSIGNED NULL,
    subscription_id BIGINT UNSIGNED NULL,
    node_id BIGINT UNSIGNED NULL,
    server_id INT(10) UNSIGNED NULL,
    message VARCHAR(500) NOT NULL,
    context_json MEDIUMTEXT NULL,
    ip_address VARCHAR(45) NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY event_type (event_type),
    KEY user_id (user_id),
    KEY admin_id (admin_id),
    KEY subscription_id (subscription_id),
    KEY node_id (node_id),
    KEY server_id (server_id),
    KEY created_at (created_at),
    CONSTRAINT fk_vpn_events_subscription FOREIGN KEY (subscription_id) REFERENCES vpn_subscriptions(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS vpn_jobs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    job_name VARCHAR(120) NOT NULL,
    payload_json MEDIUMTEXT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'pending',
    attempts INT(10) UNSIGNED NOT NULL DEFAULT 0,
    max_attempts INT(10) UNSIGNED NOT NULL DEFAULT 3,
    available_at DATETIME NULL,
    started_at DATETIME NULL,
    finished_at DATETIME NULL,
    last_error TEXT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY job_name (job_name),
    KEY status (status),
    KEY available_at (available_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS vpn_permissions (
    id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    permission VARCHAR(120) NOT NULL,
    description VARCHAR(255) NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY permission (permission)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
