CREATE TABLE IF NOT EXISTS toy_rental_rides (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    car_id INT(10) UNSIGNED NOT NULL,
    customer_name VARCHAR(255) NULL,
    customer_phone VARCHAR(50) NULL,
    started_at DATETIME NOT NULL,
    planned_end_at DATETIME NOT NULL,
    ended_at DATETIME NULL,
    duration_minutes INT(10) UNSIGNED NULL,
    payment_amount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    payment_method ENUM('cash', 'card', 'transfer', 'other') NOT NULL DEFAULT 'cash',
    payment_status ENUM('unpaid', 'paid', 'refunded') NOT NULL DEFAULT 'paid',
    status ENUM('active', 'completed', 'cancelled', 'overdue') NOT NULL DEFAULT 'active',
    notes TEXT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY car_id (car_id),
    KEY status (status),
    KEY payment_method (payment_method),
    KEY payment_status (payment_status),
    KEY started_at (started_at),
    KEY planned_end_at (planned_end_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
